import type { AuthContext } from "../auth/context";
import { isToolAllowedForAuth } from "../auth/scopes";
import type { McpToolDefinition } from "../protocol/types";
import { PERMISSIONS } from "../runtime/types";

const id = { type: "string" };
const confirm = { type: "boolean", description: "Must be true for high-risk or destructive tools" };
const challengeToken = {
  type: "string",
  description: "One-time confirmation token issued by a previous call",
};
const idempotencyKey = { type: "string", description: "Client-supplied idempotency key" };

export const TOOL_CATALOG: McpToolDefinition[] = [
  {
    name: "fairlx_workspace_list",
    description: "List workspaces the authenticated actor can access",
    inputSchema: { type: "object", properties: { limit: { type: "number" }, cursorAfter: { type: "string" } } },
    riskTier: 1,
    rateClass: "read",
    scopes: ["project:read"],
  },
  {
    name: "fairlx_project_list",
    description: "List projects in a workspace",
    inputSchema: {
      type: "object",
      properties: { workspaceId: id, limit: { type: "number" }, cursorAfter: { type: "string" } },
      required: ["workspaceId"],
    },
    riskTier: 1,
    rateClass: "read",
    scopes: ["project:read"],
    permission: PERMISSIONS.VIEW_PROJECT,
  },
  {
    name: "fairlx_project_get",
    description: "Get a project by id",
    inputSchema: { type: "object", properties: { projectId: id }, required: ["projectId"] },
    riskTier: 1,
    rateClass: "read",
    scopes: ["project:read"],
    permission: PERMISSIONS.VIEW_PROJECT,
  },
  {
    name: "fairlx_project_members_list",
    description: "List members of a project",
    inputSchema: { type: "object", properties: { projectId: id }, required: ["projectId"] },
    riskTier: 1,
    rateClass: "read",
    scopes: ["project:read"],
    permission: PERMISSIONS.VIEW_MEMBERS,
  },
  {
    name: "fairlx_work_item_list",
    description: "List work items in a project (compact fields)",
    inputSchema: {
      type: "object",
      properties: {
        projectId: id,
        sprintId: id,
        status: { type: "string" },
        type: { type: "string" },
        limit: { type: "number" },
        cursorAfter: { type: "string" },
      },
      required: ["projectId"],
    },
    riskTier: 1,
    rateClass: "read",
    scopes: ["tasks:read"],
    permission: PERMISSIONS.VIEW_TASKS,
  },
  {
    name: "fairlx_work_item_get",
    description: "Get a work item by id",
    inputSchema: { type: "object", properties: { workItemId: id }, required: ["workItemId"] },
    riskTier: 1,
    rateClass: "read",
    scopes: ["tasks:read"],
    permission: PERMISSIONS.VIEW_TASKS,
  },
  {
    name: "fairlx_sprint_list",
    description: "List sprints in a project",
    inputSchema: {
      type: "object",
      properties: { projectId: id, status: { type: "string" }, limit: { type: "number" }, cursorAfter: { type: "string" } },
      required: ["projectId"],
    },
    riskTier: 1,
    rateClass: "read",
    scopes: ["sprints:read"],
    permission: PERMISSIONS.VIEW_SPRINTS,
  },
  {
    name: "fairlx_sprint_get",
    description: "Get a sprint by id",
    inputSchema: { type: "object", properties: { sprintId: id }, required: ["sprintId"] },
    riskTier: 1,
    rateClass: "read",
    scopes: ["sprints:read"],
    permission: PERMISSIONS.VIEW_SPRINTS,
  },
  {
    name: "fairlx_link_list",
    description: "List work-item links for a work item or project",
    inputSchema: {
      type: "object",
      properties: { workItemId: id, projectId: id, limit: { type: "number" } },
    },
    riskTier: 1,
    rateClass: "read",
    scopes: ["tasks:read"],
    permission: PERMISSIONS.VIEW_TASKS,
  },
  {
    name: "fairlx_comment_list",
    description: "List comments on a work item",
    inputSchema: { type: "object", properties: { workItemId: id, limit: { type: "number" } }, required: ["workItemId"] },
    riskTier: 1,
    rateClass: "read",
    scopes: ["tasks:read"],
    permission: PERMISSIONS.VIEW_TASKS,
  },
  {
    name: "fairlx_time_log_list",
    description: "List time logs for a work item or project",
    inputSchema: {
      type: "object",
      properties: { workItemId: id, projectId: id, limit: { type: "number" } },
    },
    riskTier: 1,
    rateClass: "read",
    scopes: ["tasks:read"],
    permission: PERMISSIONS.VIEW_TASKS,
  },
  {
    name: "fairlx_doc_list",
    description: "List project documents (metadata)",
    inputSchema: { type: "object", properties: { projectId: id, limit: { type: "number" } }, required: ["projectId"] },
    riskTier: 1,
    rateClass: "read",
    scopes: ["docs:read"],
    permission: PERMISSIONS.VIEW_DOCS,
  },
  {
    name: "fairlx_doc_get",
    description: "Get a project document by id",
    inputSchema: { type: "object", properties: { docId: id, projectId: id }, required: ["docId"] },
    riskTier: 1,
    rateClass: "read",
    scopes: ["docs:read"],
    permission: PERMISSIONS.VIEW_DOCS,
  },
  {
    name: "fairlx_workflow_get",
    description: "Get the workflow, statuses, and transitions for a project",
    inputSchema: { type: "object", properties: { projectId: id }, required: ["projectId"] },
    riskTier: 1,
    rateClass: "read",
    scopes: ["workflows:read"],
    permission: PERMISSIONS.VIEW_PROJECT,
  },
  {
    name: "fairlx_agent_context_get",
    description: "Get a packed agent context for a work item (item, comments, links, sprint, project)",
    inputSchema: { type: "object", properties: { workItemId: id }, required: ["workItemId"] },
    riskTier: 1,
    rateClass: "read",
    scopes: ["tasks:read"],
    permission: PERMISSIONS.VIEW_TASKS,
  },
  {
    name: "fairlx_project_create",
    description: "Create a project in a workspace",
    inputSchema: {
      type: "object",
      properties: {
        workspaceId: id,
        name: { type: "string" },
        description: { type: "string" },
        boardType: { type: "string", enum: ["SCRUM", "KANBAN", "HYBRID"] },
        confirm,
        idempotencyKey,
      },
      required: ["workspaceId", "name"],
    },
    riskTier: 3,
    rateClass: "write",
    scopes: ["admin:manage"],
    permission: PERMISSIONS.EDIT_SETTINGS,
  },
  {
    name: "fairlx_project_update",
    description: "Update a project",
    inputSchema: {
      type: "object",
      properties: {
        projectId: id,
        name: { type: "string" },
        description: { type: "string" },
        status: { type: "string", enum: ["ACTIVE", "ON_HOLD", "COMPLETED", "ARCHIVED"] },
        confirm,
      },
      required: ["projectId"],
    },
    riskTier: 3,
    rateClass: "write",
    scopes: ["admin:manage"],
    permission: PERMISSIONS.EDIT_SETTINGS,
  },
  {
    name: "fairlx_work_item_create",
    description: "Create a work item. type defaults to TASK, priority to MEDIUM, status to TODO.",
    inputSchema: {
      type: "object",
      properties: {
        projectId: id,
        title: { type: "string" },
        type: { type: "string", enum: ["TASK", "STORY", "BUG", "EPIC", "SUBTASK", "ISSUE"] },
        priority: { type: "string", enum: ["LOW", "MEDIUM", "HIGH", "URGENT"] },
        description: { type: "string" },
        sprintId: id,
        assigneeIds: { type: "array", items: { type: "string" } },
        storyPoints: { type: "number" },
        idempotencyKey,
      },
      required: ["projectId", "title"],
    },
    riskTier: 2,
    rateClass: "write",
    scopes: ["tasks:write"],
    permission: PERMISSIONS.CREATE_TASKS,
  },
  {
    name: "fairlx_work_item_update",
    description: "Update a work item. Status changes are validated against the project workflow.",
    inputSchema: {
      type: "object",
      properties: {
        workItemId: id,
        title: { type: "string" },
        status: { type: "string" },
        priority: { type: "string" },
        description: { type: "string" },
        sprintId: id,
        assigneeIds: { type: "array", items: { type: "string" } },
        storyPoints: { type: "number" },
      },
      required: ["workItemId"],
    },
    riskTier: 2,
    rateClass: "write",
    scopes: ["tasks:write"],
    permission: PERMISSIONS.EDIT_TASKS,
  },
  {
    name: "fairlx_work_item_bulk_update",
    description: "Bulk-update work items (status, sprintId, assigneeIds, priority). Not safely retryable.",
    inputSchema: {
      type: "object",
      properties: {
        workItemIds: { type: "array", items: { type: "string" } },
        status: { type: "string" },
        sprintId: id,
        assigneeIds: { type: "array", items: { type: "string" } },
        priority: { type: "string" },
        confirm,
      },
      required: ["workItemIds"],
    },
    riskTier: 3,
    rateClass: "write",
    scopes: ["tasks:write"],
    permission: PERMISSIONS.EDIT_TASKS,
  },
  {
    name: "fairlx_work_item_split",
    description: "Split a work item into new items and create SPLIT_FROM / SPLIT_TO links",
    inputSchema: {
      type: "object",
      properties: {
        workItemId: id,
        titles: { type: "array", items: { type: "string" } },
        idempotencyKey,
      },
      required: ["workItemId", "titles"],
    },
    riskTier: 2,
    rateClass: "write",
    scopes: ["tasks:write"],
    permission: PERMISSIONS.CREATE_TASKS,
  },
  {
    name: "fairlx_sprint_create",
    description: "Create a sprint",
    inputSchema: {
      type: "object",
      properties: {
        projectId: id,
        name: { type: "string" },
        goal: { type: "string" },
        startDate: { type: "string" },
        endDate: { type: "string" },
        idempotencyKey,
      },
      required: ["projectId", "name"],
    },
    riskTier: 2,
    rateClass: "write",
    scopes: ["sprints:manage"],
    permission: PERMISSIONS.CREATE_SPRINTS,
  },
  {
    name: "fairlx_sprint_start",
    description: "Start a planned sprint. High-risk; requires confirm: true. Not safely retryable.",
    inputSchema: {
      type: "object",
      properties: { sprintId: id, confirm },
      required: ["sprintId"],
    },
    riskTier: 3,
    rateClass: "write",
    scopes: ["sprints:manage"],
    permission: PERMISSIONS.START_SPRINT,
  },
  {
    name: "fairlx_sprint_complete",
    description: "Complete an active sprint. High-risk; requires confirm: true. Not safely retryable.",
    inputSchema: {
      type: "object",
      properties: { sprintId: id, confirm },
      required: ["sprintId"],
    },
    riskTier: 3,
    rateClass: "write",
    scopes: ["sprints:manage"],
    permission: PERMISSIONS.COMPLETE_SPRINT,
  },
  {
    name: "fairlx_link_create",
    description: "Create a work-item link. BLOCKS links are cycle-checked using targetItemId.",
    inputSchema: {
      type: "object",
      properties: {
        sourceItemId: id,
        targetItemId: id,
        linkType: {
          type: "string",
          enum: [
            "BLOCKS",
            "IS_BLOCKED_BY",
            "RELATES_TO",
            "DUPLICATES",
            "IS_DUPLICATED_BY",
            "SPLIT_FROM",
            "SPLIT_TO",
            "CLONED_FROM",
            "CLONED_TO",
            "IS_CHILD_OF",
            "IS_PARENT_OF",
            "CAUSES",
            "IS_CAUSED_BY",
          ],
        },
        description: { type: "string" },
        createInverse: { type: "boolean" },
        idempotencyKey,
      },
      required: ["sourceItemId", "targetItemId", "linkType"],
    },
    riskTier: 2,
    rateClass: "write",
    scopes: ["tasks:write"],
    permission: PERMISSIONS.EDIT_TASKS,
  },
  {
    name: "fairlx_comment_add",
    description: "Add a comment to a work item",
    inputSchema: {
      type: "object",
      properties: {
        workItemId: id,
        content: { type: "string" },
        parentId: id,
        idempotencyKey,
      },
      required: ["workItemId", "content"],
    },
    riskTier: 2,
    rateClass: "write",
    scopes: ["comments:write"],
    permission: PERMISSIONS.CREATE_COMMENTS,
  },
  {
    name: "fairlx_comment_update",
    description: "Update a comment",
    inputSchema: {
      type: "object",
      properties: { commentId: id, content: { type: "string" } },
      required: ["commentId", "content"],
    },
    riskTier: 2,
    rateClass: "write",
    scopes: ["comments:write"],
    permission: PERMISSIONS.CREATE_COMMENTS,
  },
  {
    name: "fairlx_time_log_add",
    description: "Add a time log to a work item",
    inputSchema: {
      type: "object",
      properties: {
        workItemId: id,
        loggedHours: { type: "number" },
        logDate: { type: "string" },
        description: { type: "string" },
        isBillable: { type: "boolean" },
        idempotencyKey,
      },
      required: ["workItemId", "loggedHours"],
    },
    riskTier: 2,
    rateClass: "write",
    scopes: ["time:write"],
    permission: PERMISSIONS.EDIT_TASKS,
  },
  {
    name: "fairlx_doc_create",
    description: "Create a project document. Extra content is stored in description; fileId is mcp-inline when no file is uploaded.",
    inputSchema: {
      type: "object",
      properties: {
        projectId: id,
        title: { type: "string" },
        content: { type: "string" },
        category: { type: "string" },
        tags: { type: "array", items: { type: "string" } },
        idempotencyKey,
      },
      required: ["projectId", "title"],
    },
    riskTier: 2,
    rateClass: "write",
    scopes: ["docs:write"],
    permission: PERMISSIONS.CREATE_DOCS,
  },
  {
    name: "fairlx_doc_update",
    description: "Update a project document metadata / description",
    inputSchema: {
      type: "object",
      properties: {
        docId: id,
        title: { type: "string" },
        content: { type: "string" },
        category: { type: "string" },
        tags: { type: "array", items: { type: "string" } },
        isArchived: { type: "boolean" },
      },
      required: ["docId"],
    },
    riskTier: 2,
    rateClass: "write",
    scopes: ["docs:write"],
    permission: PERMISSIONS.EDIT_DOCS,
  },
  {
    name: "fairlx_custom_field_set",
    description: "Set a custom field value on a work item",
    inputSchema: {
      type: "object",
      properties: { workItemId: id, fieldId: id, value: {} },
      required: ["workItemId", "fieldId"],
    },
    riskTier: 2,
    rateClass: "write",
    scopes: ["tasks:write"],
    permission: PERMISSIONS.EDIT_TASKS,
  },
  {
    name: "fairlx_webhook_create",
    description: "Create a project webhook. High-risk; requires confirm: true.",
    inputSchema: {
      type: "object",
      properties: {
        projectId: id,
        name: { type: "string" },
        url: { type: "string" },
        events: { type: "array", items: { type: "string" } },
        secret: { type: "string" },
        confirm,
        idempotencyKey,
      },
      required: ["projectId", "name", "url", "events"],
    },
    riskTier: 3,
    rateClass: "write",
    scopes: ["admin:manage"],
    permission: PERMISSIONS.EDIT_SETTINGS,
  },
  {
    name: "fairlx_github_sync",
    description: "Mark connected GitHub repositories as syncing. High-risk; requires confirm: true. Not safely retryable.",
    inputSchema: {
      type: "object",
      properties: { projectId: id, confirm },
      required: ["projectId"],
    },
    riskTier: 3,
    rateClass: "write",
    scopes: ["admin:manage"],
    permission: PERMISSIONS.EDIT_SETTINGS,
  },
  {
    name: "fairlx_project_delete",
    description: "Delete a project. Destructive; requires confirm: true and challengeToken.",
    inputSchema: {
      type: "object",
      properties: { projectId: id, confirm, challengeToken },
      required: ["projectId"],
    },
    riskTier: 4,
    rateClass: "destructive",
    scopes: ["admin:manage"],
    permission: PERMISSIONS.DELETE_PROJECT,
  },
  {
    name: "fairlx_work_item_delete",
    description: "Delete a work item. Destructive; requires confirm: true and challengeToken.",
    inputSchema: {
      type: "object",
      properties: { workItemId: id, confirm, challengeToken },
      required: ["workItemId"],
    },
    riskTier: 4,
    rateClass: "destructive",
    scopes: ["tasks:delete"],
    permission: PERMISSIONS.DELETE_TASKS,
  },
  {
    name: "fairlx_sprint_delete",
    description: "Delete a sprint. Destructive; requires confirm: true and challengeToken.",
    inputSchema: {
      type: "object",
      properties: { sprintId: id, confirm, challengeToken },
      required: ["sprintId"],
    },
    riskTier: 4,
    rateClass: "destructive",
    scopes: ["sprints:manage"],
    permission: PERMISSIONS.DELETE_SPRINTS,
  },
  {
    name: "fairlx_link_delete",
    description: "Delete a work-item link. Destructive; requires confirm: true and challengeToken.",
    inputSchema: {
      type: "object",
      properties: { linkId: id, confirm, challengeToken },
      required: ["linkId"],
    },
    riskTier: 4,
    rateClass: "destructive",
    scopes: ["tasks:write"],
    permission: PERMISSIONS.EDIT_TASKS,
  },
  {
    name: "fairlx_comment_delete",
    description: "Delete a comment. Destructive; requires confirm: true and challengeToken.",
    inputSchema: {
      type: "object",
      properties: { commentId: id, confirm, challengeToken },
      required: ["commentId"],
    },
    riskTier: 4,
    rateClass: "destructive",
    scopes: ["comments:write"],
    permission: PERMISSIONS.DELETE_COMMENTS,
  },
  {
    name: "fairlx_time_log_delete",
    description: "Delete a time log. Destructive; requires confirm: true and challengeToken.",
    inputSchema: {
      type: "object",
      properties: { timeLogId: id, confirm, challengeToken },
      required: ["timeLogId"],
    },
    riskTier: 4,
    rateClass: "destructive",
    scopes: ["time:write"],
    permission: PERMISSIONS.EDIT_TASKS,
  },
  {
    name: "fairlx_doc_delete",
    description: "Delete a project document. Destructive; requires confirm: true and challengeToken.",
    inputSchema: {
      type: "object",
      properties: { docId: id, confirm, challengeToken },
      required: ["docId"],
    },
    riskTier: 4,
    rateClass: "destructive",
    scopes: ["docs:write"],
    permission: PERMISSIONS.DELETE_DOCS,
  },
];

export function getToolDefinition(name: string): McpToolDefinition | undefined {
  return TOOL_CATALOG.find((tool) => tool.name === name);
}

export function listToolsForClient(auth?: Pick<AuthContext, "scopes" | "projectPermissions">) {
  const tools = auth
    ? TOOL_CATALOG.filter((tool) => isToolAllowedForAuth(tool, auth))
    : TOOL_CATALOG;
  return tools.map(({ name, description, inputSchema }) => ({
    name,
    description,
    inputSchema,
  }));
}
